apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: {{ .Values.replicaCount.django }}
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag }}"
          ports:
            - containerPort: {{ .Values.django.port }}

          env:
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
            - name: DB_USER
              value: {{ .Values.env.DB_USER }}
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}

          command: ["/bin/sh"]
          args:
            - -c
            - |
              python manage.py migrate --noinput && \
              gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000
---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000