apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ .Values.replicaCount.nginx }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: {{ .Values.nginx.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    app: nginx
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      nodePort: {{ .Values.nginx.service.nodePort }}