---
- name: Setup KIND Cluster and Deploy App
  hosts: all
  become: true
  vars:
    user: ubuntu
    home_dir: /home/ubuntu
    kubeconfig_path: /home/ubuntu/.kube/config

  tasks:

    # 1. Install Docker
    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com | sh
        usermod -aG docker {{ user }}
      args:
        executable: /bin/bash

    - name: Restart Docker
      service:
        name: docker
        state: restarted

    # 2. Install kubectl
    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        executable: /bin/bash

    # 3. Install KIND
    - name: Install KIND
      shell: |
        curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
        chmod +x /usr/local/bin/kind
      args:
        executable: /bin/bash

    # 4. Create KIND cluster (idempotent)
    - name: Create KIND cluster
      shell: |
        kind get clusters | grep devops-cluster || kind create cluster --name devops-cluster
      args:
        executable: /bin/bash

    # 5. Setup kubeconfig (VERY IMPORTANT FIX)
    - name: Setup kubeconfig (FIXED)
      become: true
      shell: |
       mkdir -p /root/.kube
       kind export kubeconfig --name devops-cluster --kubeconfig /root/.kube/config

       mkdir -p /home/ubuntu/.kube
       cp /root/.kube/config /home/ubuntu/.kube/config

       chown -R ubuntu:ubuntu /home/ubuntu/.kube
       chmod 600 /home/ubuntu/.kube/config
      args:
         executable: /bin/bash

    # 6. Wait for cluster to be ready
    - name: Wait for Kubernetes nodes
      become: false
      shell: |
        export KUBECONFIG=~/.kube/config
        kubectl wait --for=condition=Ready nodes --all --timeout=180s
      args:
        executable: /bin/bash

    # 7. Verify cluster
    - name: Verify Kubernetes cluster
      become: false
      shell: |
        export KUBECONFIG=~/.kube/config
        kubectl get nodes
      args:
        executable: /bin/bash

    # 8. Install Helm
    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        executable: /bin/bash

    # 9. Clone your repo (IMPORTANT)
    - name: Clone application repo
      become: false
      git:
        repo: "https://github.com/madhul91/devops-django.git"
        dest: "{{ home_dir }}/app"

    # 10. Deploy using Helm (FINAL STEP)
    - name: Deploy/Upgrade Helm Chart
      become: false
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      kubernetes.core.helm:
        name: notes-app
        chart_ref: "{{ home_dir }}/app/django-notes-app"
        release_namespace: default
        create_namespace: true
        state: present
        values:
          django:
            image:
              repository: "{{ image_repo }}"
              tag: "{{ image_tag }}"
          nginx:
            image:
              repository: "{{ frontend_repo }}"
              tag: "{{ frontend_tag }}"
     11. Add Prometheus Repo
  # -------------------------------
  - name: Add Prometheus Helm repo
    become: false
    shell: |
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"

  # -------------------------------
  # 12. Install Monitoring Stack
  # -------------------------------
  - name: Install Prometheus + Grafana
    become: false
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"
    kubernetes.core.helm:
      name: monitoring
      chart_ref: prometheus-community/kube-prometheus-stack
      release_namespace: monitoring
      create_namespace: true
      state: present

  # -------------------------------
  # 13. Expose Grafana
  # -------------------------------
  - name: Expose Grafana via NodePort
    become: false
    shell: |
      export KUBECONFIG={{ kubeconfig_path }}
      kubectl patch svc monitoring-grafana -n monitoring \
      -p '{"spec": {"type": "NodePort"}}'
    args:
      executable: /bin/bash

  # -------------------------------
  # 14. Get Grafana Password
  # -------------------------------
  - name: Get Grafana password
    become: false
    shell: |
      export KUBECONFIG={{ kubeconfig_path }}
      kubectl get secret monitoring-grafana -n monitoring \
      -o jsonpath="{.data.admin-password}" | base64 --decode
    register: grafana_pass

  - name: Show Grafana Password
    debug:
      msg: "Grafana Password: {{ grafana_pass.stdout }}"         
